-- Le catalogue nom_certifications (Global Value Set NomCertification) datait d'une ancienne
-- version de Salesforce : plusieurs entrées ont été renommées ou retirées côté Salesforce
-- (ex: "Salesforce Certified Administrator" → "Salesforce Certified Platform Administrator"),
-- et de nouvelles ajoutées (ex: "Salesforce Certified Slack Consultant"). On désactive les
-- anciennes valeurs (sans les supprimer : des certifications existantes y font référence en
-- texte libre) et on insère le catalogue à jour, lu depuis le fichier XML Salesforce actuel
-- NomCertification.globalValueSet-meta.xml.

update nom_certifications set actif = false
where nom in (
  'Salesforce Certified Administrator',
  'Salesforce Certified Advanced Administrator',
  'Salesforce Certified Platform Developer I',
  'Salesforce Certified JavaScript Developer I',
  'Salesforce Certified Technical Architect',
  'Salesforce Certified Data Architecture & Management Designer',
  'Salesforce Certified Sharing and Visibility Designer',
  'Salesforce Certified Integration Architecture Designer',
  'Salesforce Certified Identity and Access Management Designer',
  'Salesforce Certified Development Lifecycle and Deployment Designer',
  'Salesforce Certified Financial Services Cloud Consultant',
  'Salesforce Certified Marketing Cloud Consultant',
  'Salesforce Certified Pardot Consultant',
  'Salesforce Certified CPQ Specialist',
  'Salesforce Certified Marketing Cloud Administrator',
  'Salesforce Certified Marketing Cloud Developer',
  'Salesforce Certified AI Specialist',
  'Salesforce Certified Associate',
  'Salesforce Certified Tableau CRM & Einstein Discovery Consultant',
  'Advanced Billing Accredited Professional',
  'B2B Solution Architect Accredited Professional',
  'B2C Solution Architect Accredited Professional',
  'Energy & Utilities Cloud Accredited Professional',
  'Gonexa Doc Accredited Professional',
  'Industries CPQ Accredited Professional',
  'MuleSoft Accredited Integration Architect',
  'OmniStudio Developer Accredited Professional',
  'Revenue Cloud Accredited Professional',
  'Salesforce Billing Accredited Professional',
  'Salesforce Connect Accredited Professional',
  'Salesforce for Slack Accredited Professional',
  'Slack Ambassador Accredited Professional',
  'Vlocity Insurance Accredited Professional'
);

insert into nom_certifications (nom, categorie, ordre) values
('Salesforce Certified Agentforce Specialist', 'Certification', 1),
('Salesforce Certified AI Associate', 'Certification', 2),
('Salesforce Certified Application Architect', 'Certification', 3),
('Salesforce Certified B2B Solution Architect', 'Certification', 4),
('Salesforce Certified B2C Solution Architect', 'Certification', 5),
('Salesforce Certified Business Analyst', 'Certification', 6),
('Salesforce Certified CPQ Administrator', 'Certification', 7),
('Salesforce Certified CRM Analytics and Einstein Discovery Consultant', 'Certification', 8),
('Salesforce Certified Data Cloud Consultant', 'Certification', 9),
('Salesforce Certified Education Cloud Consultant', 'Certification', 10),
('Salesforce Certified Experience Cloud Consultant', 'Certification', 11),
('Salesforce Certified Field Service Consultant', 'Certification', 12),
('Salesforce Certified Health Cloud Consultant', 'Certification', 13),
('Salesforce Certified Industries CPQ Developer', 'Certification', 14),
('Salesforce Certified JavaScript Developer', 'Certification', 15),
('Salesforce Certified Marketing Cloud Account Engagement Consultant', 'Certification', 16),
('Salesforce Certified Marketing Cloud Account Engagement Specialist', 'Certification', 17),
('Salesforce Certified Marketing Cloud Email Specialist', 'Certification', 18),
('Salesforce Certified Marketing Cloud Engagement Administrator', 'Certification', 19),
('Salesforce Certified Marketing Cloud Engagement Consultant', 'Certification', 20),
('Salesforce Certified Marketing Cloud Engagement Developer', 'Certification', 21),
('Salesforce Certified MuleSoft Developer', 'Certification', 22),
('Salesforce Certified MuleSoft Integration Foundations', 'Certification', 23),
('Salesforce Certified MuleSoft Platform Architect', 'Certification', 24),
('Salesforce Certified Nonprofit Cloud Consultant', 'Certification', 25),
('Salesforce Certified OmniStudio Consultant', 'Certification', 26),
('Salesforce Certified OmniStudio Developer', 'Certification', 27),
('Salesforce Certified Platform Administrator', 'Certification', 28),
('Salesforce Certified Platform Administrator II', 'Certification', 29),
('Salesforce Certified Platform App Builder', 'Certification', 30),
('Salesforce Certified Platform Data Architect', 'Certification', 31),
('Salesforce Certified Platform Developer', 'Certification', 32),
('Salesforce Certified Platform Developer II', 'Certification', 33),
('Salesforce Certified Platform Development Lifecycle and Deployment Architect', 'Certification', 34),
('Salesforce Certified Platform Foundations', 'Certification', 35),
('Salesforce Certified Platform Identity and Access Management Architect', 'Certification', 36),
('Salesforce Certified Platform Integration Architect', 'Certification', 37),
('Salesforce Certified Platform Sharing and Visibility Architect', 'Certification', 38),
('Salesforce Certified Platform User Experience Designer', 'Certification', 39),
('Salesforce Certified Revenue Cloud Consultant', 'Certification', 40),
('Salesforce Certified Sales Cloud Consultant', 'Certification', 41),
('Salesforce Certified Service Cloud Consultant', 'Certification', 42),
('Salesforce Certified Slack Consultant', 'Certification', 43),
('Salesforce Certified System Architect', 'Certification', 44),
('Advanced Field Service Accredited Professional', 'Accreditation', 100),
('B2B Commerce Administrator Accredited Professional', 'Accreditation', 101),
('B2B Commerce Developer Accredited Professional', 'Accreditation', 102),
('Consumer Goods Cloud Accredited Professional', 'Accreditation', 103),
('Contact Center Accredited Professional', 'Accreditation', 104),
('CPQ and Billing Consultant Accredited Professional', 'Accreditation', 105),
('Energy and Utilities Cloud Accredited Professional', 'Accreditation', 106),
('Financial Services Cloud Accredited Professional', 'Accreditation', 107),
('Health Cloud Accredited Professional', 'Accreditation', 108),
('Heroku Developer Accredited Professional', 'Accreditation', 109),
('Loyalty Management Accredited Professional', 'Accreditation', 110),
('Manufacturing Cloud Accredited Professional', 'Accreditation', 111),
('Marketing Cloud Advanced Cross Channel Accredited Professional', 'Accreditation', 112),
('Marketing Cloud Intelligence Accredited Professional', 'Accreditation', 113),
('Marketing Cloud Personalization Accredited Professional', 'Accreditation', 114),
('Media Cloud Accredited Professional', 'Accreditation', 115),
('Net Zero Cloud Accredited Professional', 'Accreditation', 116),
('Order Management Administrator Accredited Professional', 'Accreditation', 117),
('Order Management Developer Accredited Professional', 'Accreditation', 118),
('Process Automation Accredited Professional', 'Accreditation', 119),
('Public Sector Solutions Accredited Professional', 'Accreditation', 120)
on conflict (nom) do nothing;
